version: '3'
services: 
  backend: 
    build: 
      context: backend
      dockerfile: Dockerfile
    #volumes: 
     # - "./backend:/usr/src/app"
    ports:
      - "3000:3000" 
    networks:
      - myytnetwork

  neo4j: 
    image: neo4j:3.5
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - myytnetwork

networks:
  myytnetwork:
    driver: bridge
