version: '3'
services: 
  backend: 
    build: ./backend
    command: node app
    #volumes: 
     # - "./backend:/usr/src/app"
    ports:
      - "3000:3000"
    networks:
      - myytnetwork
   # environment:
   #   - MESSAGE_QUEUE=amqp://rabbitmq
   # links:
   #   - rabbitmq

  neo4j: 
    image: neo4j:3.5
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - myytnetwork

  rabbitmq:
    image: 'rabbitmq:3.7-management-alpine'
    ports:
        - 15672:15672
        - 5672:5672
    networks:
    - notifications-net

networks:
  myytnetwork:
    driver: bridge
